# Generated by Django 4.2.9 on 2024-01-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=10)),
                ('designation', models.CharField(choices=[('Associate', 'Associate'), ('TL', 'TL'), ('Manager', 'Manager')], max_length=50)),
                ('Start_date', models.DateTimeField(auto_now_add=True)),
                ('End_date', models.DateTimeField(auto_now_add=True)),
                ('Salary', models.IntegerField(max_length=50)),
                ('Promotion', models.IntegerField(max_length=60)),
            ],
        ),
    ]
