# Generated by Django 4.2.9 on 2024-01-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='date_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='Empapp.daterange'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='Empapp.employee'),
        ),
    ]
