# Generated by Django 4.2.9 on 2024-01-21 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0002_employeesalary_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='num_employees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
