# Generated by Django 4.2.9 on 2024-01-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0004_remove_employee_num_employees_employee_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary_by_month',
            field=models.DecimalField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
