# Generated by Django 4.2.9 on 2024-01-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0005_remove_employee_age_employeesalary_salary_by_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesalary',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='salary_by_month',
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='date_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empapp.daterange'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
