# Generated by Django 4.2.9 on 2024-01-22 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Empapp', '0006_remove_employeesalary_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='salary_by_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='daterange',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='date_range',
            field=models.CharField(choices=[('start_date', 'Start Date'), ('end_date', 'End Date')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
